#!/usr/bin/env bash

set -eu

export TARGET="$WD/bin/main"

now () {
    date +%s.%N
}

build_all () {
    flags=(
        "-std=c99" \
        -Werror -Wall -Wextra -Wsign-conversion -Wunused -Wunused-function \
        -Wunused-label -Wunused-macros -Wunused-parameter -Wunused-value \
        -Wunused-variable -Wcast-align -Wcast-qual -Wmissing-declarations \
        -Wredundant-decls -Wmissing-prototypes -Wnested-externs \
        -Wpointer-arith -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch \
        -Wmissing-field-initializers
    )
    srcs=(
        lib
        main
    )
    cp "$WD/src"/* "$WD/build"
    cd "$WD/build" || exit 1
    for x in "${srcs[@]/%/.c}"; do
        echo "Compiling $x"
        cc "${flags[@]}" -c "$x"
    done
    echo "Linking..."
    cc "${flags[@]}" -lpthread "${srcs[@]/%/.o}" -o "$TARGET"
}

(
    start=$(now)
    clang-format -i -verbose "$WD/src"/* 2>&1 | sed 's/\/.*\///g'
    build_all
    python3 -c "print(\"Done! ({:.3f}s)\n\".format($(now) - ${start}))"
)

echo "$ $TARGET"
"$TARGET"
